# Generated by Django 5.2.5 on 2025-09-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sosalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedcontact',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
